local ZygorGuidesViewer=ZygorGuidesViewer
if not ZygorGuidesViewer then return end
if UnitFactionGroup("player")~="Alliance" then return end
if ZGV:DoMutex("TitlesA") then return end
ZygorGuidesViewer.GuideMenuTier = "TRI"
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Burning Crusade Titles\\Player versus Player\\Justicar")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Burning Crusade Titles\\Reputations\\Of the Shattered Sun")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Wrath of the Lich King Titles\\Dungeons & Raids\\The Astral Walker")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Wrath of the Lich King Titles\\Dungeons & Raids\\Bane of the Fallen King")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Wrath of the Lich King Titles\\Dungeons & Raids\\Champion of the Frozen Wastes")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Wrath of the Lich King Titles\\Dungeons & Raids\\Herald of the Titans")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Wrath of the Lich King Titles\\Dungeons & Raids\\The Kingslayer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Wrath of the Lich King Titles\\Dungeons & Raids\\The Light of Dawn")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Wrath of the Lich King Titles\\Dungeons & Raids\\Of the Nightfall")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Wrath of the Lich King Titles\\Dungeons & Raids\\The Patient")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Wrath of the Lich King Titles\\Dungeons & Raids\\Starcaller")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Wrath of the Lich King Titles\\Dungeons & Raids\\Twilight Vanquisher")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Wrath of the Lich King Titles\\Player versus Player\\of the Alliance")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Wrath of the Lich King Titles\\Player versus Player\\Arena Master")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Cooking\\Hail to the Chef")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Cooking\\Second That Emotion")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Cooking\\Sous Chef")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Cooking\\The Outland Gourmet")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Cooking\\The Northrend Gourmet")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Cooking\\The Cake Is Not A Lie")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Cooking\\Critter Gitter")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Cooking\\Grand Master Cook")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Cooking\\Our Daily Bread")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Cooking\\Kickin' It Up a Notch")
ZygorGuidesViewer:RegisterGuidePlaceholder("Achievement Guides\\Professions\\Cooking\\Dinner Impossible")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Wrath of the Lich King Titles\\Professions\\Fishing\\Salty")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Wrath of the Lich King Titles\\Quests\\The Loremaster")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Wrath of the Lich King Titles\\Quests\\Loremaster of Kalimdor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Wrath of the Lich King Titles\\Quests\\Loremaster of Eastern Kingdoms")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Wrath of the Lich King Titles\\Quests\\Loremaster of Outlands")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Wrath of the Lich King Titles\\Quests\\Loremaster of Northrend")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Wrath of the Lich King Titles\\Quests\\Loremaster of Cataclysm")
ZygorGuidesViewer:RegisterGuidePlaceholder("Reputation Guides\\Classic Reputations\\Argent Dawn")
ZygorGuidesViewer:RegisterGuidePlaceholder("Reputation Guides\\Wrath of the Lich King Reputations\\Argent Crusade")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Wrath of the Lich King Titles\\Exalted Argent Champion of the Alliance")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Cataclysm Titles\\Dungeons & Raids\\Blackwing's Bane")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Cataclysm Titles\\Dungeons & Raids\\Defender of a Shattered World")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Cataclysm Titles\\Dungeons & Raids\\Destroyer's End")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Cataclysm Titles\\Dungeons & Raids\\Dragonslayer")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Cataclysm Titles\\Dungeons & Raids\\Firelord")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Cataclysm Titles\\Dungeons & Raids\\Of the Four Winds")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Cataclysm Titles\\Dungeons & Raids\\Savior of Azeroth")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Cataclysm Titles\\General\\The Camel-Hoarder")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Cataclysm Titles\\Professions\\Archaeology\\Assistant Professor, Associate Professor, and Professor")
ZygorGuidesViewer:RegisterGuidePlaceholder("Title Guides\\Cataclysm Titles\\Quests\\The Flamebreaker")
